package com.rudearts.recipesearcher.data.model.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "recipe".
 */
@Entity(nameInDb = "recipe")
public class RecipeDb {

    @Id(autoincrement = true)
    private Long id;
    private String title;
    private String description;
    private String imageUrl;
    private String contentUrl;

    @Generated
    public RecipeDb() {
    }

    public RecipeDb(Long id) {
        this.id = id;
    }

    @Generated
    public RecipeDb(Long id, String title, String description, String imageUrl, String contentUrl) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.imageUrl = imageUrl;
        this.contentUrl = contentUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getContentUrl() {
        return contentUrl;
    }

    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl;
    }

}
